# Generated by Django 3.2.7 on 2021-11-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('social', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='company')),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='location',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='name',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='page',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='website',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.company'),
        ),
    ]
