# Generated by Django 3.2.7 on 2021-11-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_auto_20211112_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='serviceprovider',
            name='company',
        ),
        migrations.AddField(
            model_name='billing',
            name='account_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
